//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.25 at 01:34:45 PM CEST 
//


package tn.bz.schema.majcrsalltndcvv3;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tn.bz.schema.majcrsalltndcvv3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tn.bz.schema.majcrsalltndcvv3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Document.Extraits }
     * 
     */
    public Document.Extraits createDocumentExtraits() {
        return new Document.Extraits();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait }
     * 
     */
    public Document.Extraits.Extrait createDocumentExtraitsExtrait() {
        return new Document.Extraits.Extrait();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait.Details }
     * 
     */
    public Document.Extraits.Extrait.Details createDocumentExtraitsExtraitDetails() {
        return new Document.Extraits.Extrait.Details();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait.Details.Detail }
     * 
     */
    public Document.Extraits.Extrait.Details.Detail createDocumentExtraitsExtraitDetailsDetail() {
        return new Document.Extraits.Extrait.Details.Detail();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait.Entete }
     * 
     */
    public Document.Extraits.Extrait.Entete createDocumentExtraitsExtraitEntete() {
        return new Document.Extraits.Extrait.Entete();
    }

    /**
     * Create an instance of {@link Document.EnteteDoc }
     * 
     */
    public Document.EnteteDoc createDocumentEnteteDoc() {
        return new Document.EnteteDoc();
    }

    /**
     * Create an instance of {@link TMontant }
     * 
     */
    public TMontant createTMontant() {
        return new TMontant();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait.Details.Detail.RefOperation }
     * 
     */
    public Document.Extraits.Extrait.Details.Detail.RefOperation createDocumentExtraitsExtraitDetailsDetailRefOperation() {
        return new Document.Extraits.Extrait.Details.Detail.RefOperation();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait.Details.Detail.RefAutorisationBct }
     * 
     */
    public Document.Extraits.Extrait.Details.Detail.RefAutorisationBct createDocumentExtraitsExtraitDetailsDetailRefAutorisationBct() {
        return new Document.Extraits.Extrait.Details.Detail.RefAutorisationBct();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait.Entete.Titulaire }
     * 
     */
    public Document.Extraits.Extrait.Entete.Titulaire createDocumentExtraitsExtraitEnteteTitulaire() {
        return new Document.Extraits.Extrait.Entete.Titulaire();
    }

    /**
     * Create an instance of {@link Document.Extraits.Extrait.Entete.RefCompte }
     * 
     */
    public Document.Extraits.Extrait.Entete.RefCompte createDocumentExtraitsExtraitEnteteRefCompte() {
        return new Document.Extraits.Extrait.Entete.RefCompte();
    }

}
